### Fruit Recommendation System using Content-Based Filtering and Cosine Similarity

# Problem Statement

People often want to choose foods with similar nutritional values for:

    healthy diet planning
    
    nutritional substitution
    
    meal recommendations

However, it is difficult to manually compare the nutritional values of many fruits.

Therefore, we build a recommendation system that automatically finds nutritionally similar fruits.

| Column      | Description    |
| ----------- | -------------- |
| fruit_100g  | Name of fruit  |
| energy_kcal | Energy content |
| water_g     | Water content  |
| protein_g   | Protein        |
| fat_g       | Fat            |
| fiber_g     | Dietary fiber  |
| sugars_g    | Sugar content  |
| vitaminc_mg | Vitamin C      |

In [32]:
import os
os.listdir()

['.ipynb_checkpoints',
 '1 Fruit_recommenders.ipynb',
 'app.py',
 'Content based Recom Sysem.pptx',
 'Def Rec.ipynb',
 'fruit_dataset_100.csv',
 'fruit_nutrition.csv',
 'requirements.txt']

In [33]:

import pandas as pd

from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

In [34]:
# Load data

df = pd.read_csv("fruit_dataset_100.csv")
df

,fruit_100g,energy_kcal,water_g,protein_g,totalfat_g,fiber_g,sugars_g,vitaminc_mg
0,Banana,51.1,77.9,2.95,3.17,3.99,17.64,27.6
1,Apple,228.8,70.0,1.38,4.05,4.49,7.17,67.4
2,Orange,233.4,88.9,2.01,13.11,1.21,22.34,28.2
3,Lemon,242.1,84.5,1.67,10.74,1.07,24.93,66.6
4,Lime,231.1,81.9,1.00,8.82,2.25,7.57,16.0
...,...,...,...,...,...,...,...,...
95,Longan_95,30.7,77.7,1.09,0.19,3.37,5.29,85.4
96,Soursop_96,169.1,67.6,2.75,8.07,9.14,9.72,69.0
97,Breadfruit_97,127.2,74.3,0.89,7.56,2.65,10.15,77.2
98,Banana_98,223.4,69.8,3.35,13.08,2.90,1.42,33.1
99,Apple_99,22.0,60.2,1.83,0.21,6.66,7.06,78.9

In [35]:
# Set fruit name as index

df = df.set_index("fruit_100g")

df.index.name = None

In [36]:
df.head()

,energy_kcal,water_g,protein_g,totalfat_g,fiber_g,sugars_g,vitaminc_mg
Banana,51.1,77.9,2.95,3.17,3.99,17.64,27.6
Apple,228.8,70.0,1.38,4.05,4.49,7.17,67.4
Orange,233.4,88.9,2.01,13.11,1.21,22.34,28.2
Lemon,242.1,84.5,1.67,10.74,1.07,24.93,66.6
Lime,231.1,81.9,1.00,8.82,2.25,7.57,16.0

In [37]:
# Use ALL numeric columns automatically

features = df.select_dtypes(include=['number'])

In [38]:
features.index

Index(['Banana', 'Apple', 'Orange', 'Lemon', 'Lime', 'Mango', 'Peach',
       'Pineapple', 'Grapes', 'Strawberry', 'Blueberry', 'Raspberry',
       'Blackberry', 'Watermelon', 'Muskmelon', 'Pomegranate', 'Pear', 'Plum',
       'Cherry', 'Apricot', 'Avocado', 'Coconut', 'Fig', 'Date', 'Dragonfruit',
       'Lychee', 'Jackfruit', 'Guava', 'Custard Apple', 'Kiwi', 'Papaya',
       'Passionfruit', 'Cranberry', 'Mulberry', 'Gooseberry', 'Tamarind',
       'Sapota', 'Starfruit', 'Rambutan', 'Durian', 'Persimmon', 'Nectarine',
       'Olive', 'Boysenberry', 'Elderberry', 'Acai', 'Longan', 'Soursop',
       'Breadfruit', 'Banana_49', 'Apple_50', 'Orange_51', 'Lemon_52',
       'Lime_53', 'Mango_54', 'Peach_55', 'Pineapple_56', 'Grapes_57',
       'Strawberry_58', 'Blueberry_59', 'Raspberry_60', 'Blackberry_61',
       'Watermelon_62', 'Muskmelon_63', 'Pomegranate_64', 'Pear_65', 'Plum_66',
       'Cherry_67', 'Apricot_68', 'Avocado_69', 'Coconut_70', 'Fig_71',
       'Date_72', 'Dragonfruit_73', 'Lychee_74', 'Jackfruit_75', 'Guava_76',
       'Custard Apple_77', 'Kiwi_78', 'Papaya_79', 'Passionfruit_80',
       'Cranberry_81', 'Mulberry_82', 'Gooseberry_83', 'Tamarind_84',
       'Sapota_85', 'Starfruit_86', 'Rambutan_87', 'Durian_88', 'Persimmon_89',
       'Nectarine_90', 'Olive_91', 'Boysenberry_92', 'Elderberry_93',
       'Acai_94', 'Longan_95', 'Soursop_96', 'Breadfruit_97', 'Banana_98',
       'Apple_99'],
      dtype='object')

In [39]:
#  APPLY SCALING HERE

scaler = MinMaxScaler()

features_scaled = scaler.fit_transform(features)

In [40]:
features_scaled

array([[0.11256354, 0.51603499, 0.84735202, 0.20452986, 0.36853221,
        0.69382612, 0.26109391],
       [0.75780683, 0.28571429, 0.35825545, 0.26492793, 0.42133052,
        0.25409492, 0.67182663],
       [0.7745098 , 0.83673469, 0.55451713, 0.8867536 , 0.0749736 ,
        0.89122218, 0.26728586],
       [0.80610022, 0.70845481, 0.44859813, 0.7240906 , 0.06019007,
        1.        , 0.66357069],
       [0.76615832, 0.63265306, 0.23987539, 0.59231297, 0.18479409,
        0.27089458, 0.14138287],
       [0.07443718, 0.11953353, 0.105919  , 0.702814  , 0.58922914,
        0.48677026, 0.54385965],
       [0.89215686, 0.2361516 , 0.01246106, 0.73026767, 0.        ,
        0.61066779, 0.97316821],
       [0.98184459, 0.93877551, 0.24299065, 0.44543583, 0.22597677,
        0.39941201, 0.750258  ],
       [0.9778504 , 0.82507289, 0.34267913, 0.55044612, 0.61140444,
        0.75178496, 0.47884417],
       [0.79557008, 0.6909621 , 0.        , 0.37199725, 0.23020063,
        0.65812684, 0.18988648],
       [0.97167756, 0.98542274, 0.89096573, 0.08304736, 0.24392819,
        0.94120118, 0.29514964],
       [0.48184459, 0.4548105 , 0.82242991, 0.52916953, 0.12143611,
        0.75178496, 0.6119711 ],
       [0.63834423, 0.62973761, 0.79439252, 0.62319835, 0.54804646,
        0.78790424, 0.26625387],
       [0.90123457, 0.34402332, 0.18068536, 0.37336994, 0.19218585,
        0.37547249, 0.67905057],
       [0.86891794, 0.35860058, 0.26168224, 0.61358957, 0.02956705,
        0.32801344, 0.11764706],
       [0.39869281, 0.89504373, 0.40809969, 0.77899794, 0.73495248,
        0.85762285, 0.83488132],
       [0.46187364, 0.16618076, 0.21183801, 0.97323267, 0.49419219,
        0.51322974, 0.26934985],
       [0.22766885, 0.24198251, 0.56074766, 0.5271105 , 0.50791975,
        0.48635027, 0.0505676 ],
       [0.87872186, 0.19241983, 0.14330218, 0.0672615 , 0.35691658,
        0.47333053, 0.46852425],
       [0.61692084, 0.46938776, 0.65732087, 0.74811256, 0.23020063,
        0.01679966, 0.01341589],
       [0.25780683, 0.21574344, 0.97507788, 0.14344544, 0.56177402,
        0.45065099, 0.46439628],
       [0.39506173, 0.41399417, 0.73208723, 0.48249828, 0.63463569,
        0.57244855, 0.20743034],
       [0.92120552, 0.88046647, 0.18068536, 0.53054221, 1.        ,
        0.60436791, 0.09184727],
       [0.59622367, 0.39650146, 0.63239875, 0.63898421, 0.92713833,
        0.25451491, 0.2755418 ],
       [0.99419027, 0.8483965 , 0.41744548, 0.49004804, 0.82998944,
        0.75556489, 0.46439628],
       [0.92193174, 0.84548105, 0.78193146, 0.96431023, 0.99577614,
        0.56404872, 0.70381837],
       [0.59840232, 0.85422741, 0.40498442, 0.23884695, 0.79514256,
        0.21419572, 0.51083591],
       [0.96151053, 0.46355685, 0.67601246, 0.07275223, 0.43400211,
        0.07937841, 0.83178535],
       [0.84604212, 0.11953353, 0.67601246, 0.41523679, 0.2280887 ,
        0.47627047, 0.67595459],
       [0.43173566, 0.38483965, 0.82242991, 0.85998627, 0.69165787,
        0.69172617, 0.32714138],
       [0.61728395, 0.55102041, 0.33333333, 0.26149623, 0.91341077,
        0.13607728, 0.38080495],
       [0.87981118, 0.67055394, 0.89719626, 0.92038435, 0.75079197,
        0.75346493, 0.81011352],
       [0.25889615, 0.9154519 , 0.7788162 , 0.57515443, 0.25131996,
        0.92608148, 0.91537668],
       [0.92737836, 0.696793  , 0.08099688, 0.53740563, 0.69904963,
        0.13943721, 0.91021672],
       [0.        , 0.75218659, 0.37383178, 0.73369938, 0.15417107,
        0.08063839, 1.        ],
       [0.25344953, 0.6851312 , 0.82866044, 0.05490734, 0.80147835,
        0.27089458, 0.33436533],
       [0.97930283, 0.66472303, 0.19314642, 0.59917639, 0.55332629,
        0.37421252, 0.73993808],
       [0.23565723, 0.94752187, 0.27725857, 0.49485244, 0.55332629,
        0.35069299, 0.02889577],
       [0.37436456, 0.06705539, 0.79127726, 0.1050103 , 0.6842661 ,
        0.38303234, 0.88235294],
       [0.986565  , 0.74052478, 0.40809969, 0.67673301, 0.6156283 ,
        0.76186476, 0.40557276],
       [0.82171387, 0.99708455, 0.13395639, 0.12216884, 0.19746568,
        0.21419572, 0.73271414],
       [0.23965142, 0.25655977, 0.30218069, 0.3973919 , 0.74023231,
        0.03401932, 0.20536636],
       [0.57806826, 0.9212828 , 0.82866044, 0.37131091, 0.98416051,
        0.95800084, 0.66047472],
       [0.24074074, 0.80466472, 0.09034268, 0.64378861, 0.47518479,
        0.38051239, 0.92776058],
       [0.99237473, 0.3148688 , 0.96884735, 0.27247769, 0.02217529,
        0.1297774 , 0.97316821],
       [0.83442266, 0.76093294, 0.00311526, 0.15648593, 0.65892291,
        0.88828223, 0.78947368],
       [0.46550472, 0.05539359, 0.8411215 , 0.70075498, 0.15733897,
        0.6598068 , 0.97626419],
       [0.01742919, 0.62682216, 0.59190031, 0.78723404, 0.91974657,
        0.28895422, 0.35397317],
       [0.71278141, 0.50145773, 0.01869159, 0.61153054, 0.93875396,
        0.54136917, 0.66769866],
       [0.15105301, 0.05247813, 0.41744548, 0.94921071, 0.24815206,
        0.48299034, 0.00515996],
       [0.77160494, 0.16326531, 0.29283489, 0.28620453, 0.39809926,
        0.70264595, 0.38596491],
       [0.75889615, 0.58892128, 0.86604361, 0.77213452, 0.67687434,
        0.52582948, 0.70072239],
       [0.63979666, 0.95043732, 0.8317757 , 0.04529856, 0.87539599,
        0.14069719, 0.4127967 ],
       [0.77487291, 0.88338192, 0.92523364, 0.29238161, 0.16789863,
        0.33809324, 0.3003096 ],
       [0.5617284 , 0.62682216, 0.        , 0.90391215, 0.87222809,
        0.40823184, 0.15789474],
       [0.35112564, 0.65306122, 0.69470405, 0.45573095, 0.24709609,
        0.84292314, 0.17234262],
       [0.3275236 , 0.58600583, 0.98130841, 0.72958133, 0.05491024,
        0.        , 0.82043344],
       [0.22839506, 0.63265306, 0.8317757 , 0.11461908, 0.43928194,
        0.3901722 , 0.90815273],
       [0.91249092, 0.82215743, 0.52024922, 0.89636239, 0.41605069,
        0.34775304, 0.94014448],
       [0.7033406 , 0.48396501, 0.18380062, 0.32395333, 0.40443506,
        0.51532969, 0.27244582],
       [0.36637618, 0.78425656, 0.46728972, 0.34179822, 0.27349525,
        0.59470811, 0.8255934 ],
       [0.95606391, 0.96209913, 0.26168224, 0.59094029, 0.57127772,
        0.88576228, 0.55314757],
       [0.51924473, 0.31195335, 0.38006231, 0.62045299, 0.99894403,
        0.02813944, 0.41486068],
       [0.90885984, 0.6909621 , 0.85046729, 0.3431709 , 0.76768743,
        0.09701806, 0.1744066 ],
       [0.30065359, 0.08163265, 0.90342679, 0.27453672, 0.34741288,
        0.10247795, 0.27760578],
       [0.90450254, 0.09912536, 0.6635514 , 1.        , 0.64413939,
        0.11633767, 0.99380805],
       [0.5620915 , 0.90087464, 0.7165109 , 0.46533974, 0.71383316,
        0.59134817, 0.0247678 ],
       [0.08533043, 0.44023324, 0.65109034, 0.74262183, 0.30411827,
        0.22637547, 0.29721362],
       [0.45896877, 0.24781341, 0.47040498, 0.59780371, 0.91446674,
        0.48803024, 0.77089783],
       [0.23166304, 0.5335277 , 0.29283489, 0.81331503, 0.92291447,
        0.41327173, 0.0505676 ],
       [0.1281772 , 0.93002915, 0.33021807, 0.18943034, 0.35269271,
        0.55438891, 0.99277606],
       [0.38743646, 0.63265306, 0.40498442, 0.35552505, 0.24392819,
        0.78244435, 0.25799794],
       [0.31045752, 0.58892128, 0.92211838, 0.38229238, 0.73495248,
        0.68374633, 0.7131063 ],
       [0.39869281, 0.40524781, 0.65420561, 0.68771448, 0.03590285,
        0.4951701 , 0.02992776],
       [0.57371097, 0.42565598, 0.46728972, 0.03157172, 0.01689546,
        0.80218396, 0.58307534],
       [0.02360203, 0.66763848, 0.57632399, 0.15168154, 0.11404435,
        0.80806384, 0.63054696],
       [0.83478577, 0.6122449 , 0.62305296, 0.86684969, 0.10242872,
        0.45947081, 0.68627451],
       [0.09331881, 0.30612245, 0.66978193, 0.46533974, 0.86906019,
        0.73288534, 0.55521156],
       [0.32207698, 0.9212828 , 0.4517134 , 0.09951956, 0.34952482,
        0.62200756, 0.47162023],
       [0.40559187, 0.31778426, 0.89096573, 0.25875086, 0.97043295,
        0.10835783, 0.78328173],
       [0.93427741, 0.03498542, 0.23364486, 0.65271105, 0.42027455,
        0.40361193, 0.98039216],
       [0.54393609, 0.01749271, 0.73208723, 0.48730268, 0.88595565,
        0.16337673, 0.        ],
       [0.81336238, 0.99708455, 0.55140187, 0.76801647, 0.29883844,
        0.34901302, 0.61403509],
       [0.08351489, 0.98542274, 0.91588785, 0.69595058, 0.40654699,
        0.06383872, 0.71620227],
       [0.28540305, 1.        , 0.74454829, 0.8702814 , 0.94297782,
        0.10919782, 0.33952528],
       [0.60348584, 0.1516035 , 0.69470405, 0.40974605, 0.97571278,
        0.29651407, 0.84313725],
       [0.70660857, 0.05539359, 0.83489097, 0.47975292, 0.59028511,
        0.60352793, 0.69246646],
       [0.2037037 , 0.50145773, 0.52024922, 0.93617021, 0.3780359 ,
        0.63544729, 0.74819401],
       [0.33405955, 0.00291545, 0.18068536, 0.13658202, 0.85427666,
        0.62284754, 0.14138287],
       [0.76797386, 0.75510204, 0.19937695, 0.91352093, 0.18479409,
        0.76270475, 0.03921569],
       [0.32207698, 0.0058309 , 1.        , 0.89910776, 0.42977825,
        0.54682906, 0.49329205],
       [0.9644154 , 0.19825073, 0.30529595, 0.41111874, 0.65153115,
        0.47711046, 0.91434469],
       [1.        , 0.20408163, 0.57632399, 0.72889499, 0.40865892,
        0.11549769, 0.29824561],
       [0.06572259, 0.78717201, 0.94392523, 0.14893617, 0.48574446,
        0.80260395, 0.83591331],
       [0.15976761, 0.08163265, 0.51090343, 0.07000686, 0.48574446,
        0.41663167, 0.50154799],
       [0.03848947, 0.51020408, 0.26791277, 0.        , 0.3030623 ,
        0.1751365 , 0.85758514],
       [0.54103123, 0.21574344, 0.78504673, 0.54083734, 0.9123548 ,
        0.36119278, 0.68833849],
       [0.38888889, 0.41107872, 0.20560748, 0.50583391, 0.22703273,
        0.37925241, 0.77296182],
       [0.73819898, 0.27988338, 0.97196262, 0.88469458, 0.25343189,
        0.01259975, 0.31785346],
       [0.00689906, 0.        , 0.49844237, 0.00137268, 0.65047518,
        0.24947501, 0.79050568]])

In [41]:
# Compute cosine similarity

similarity_matrix = cosine_similarity(features_scaled)

In [42]:
similarity_matrix

array([[1.        , 0.67179355, 0.79486392, ..., 0.69378135, 0.68041712,
        0.68118676],
       [0.67179355, 1.        , 0.75493967, ..., 0.90066029, 0.78313509,
        0.72588406],
       [0.79486392, 0.75493967, 1.        , ..., 0.82426252, 0.78311125,
        0.3633626 ],
       ...,
       [0.69378135, 0.90066029, 0.82426252, ..., 1.        , 0.7204061 ,
        0.69268681],
       [0.68041712, 0.78313509, 0.78311125, ..., 0.7204061 , 1.        ,
        0.49218151],
       [0.68118676, 0.72588406, 0.3633626 , ..., 0.69268681, 0.49218151,
        1.        ]], shape=(100, 100))

In [43]:
# Convert to DataFrame

similarity_df = pd.DataFrame(
    similarity_matrix,
    index=features.index,
    columns=features.index
)

In [44]:
similarity_df

,Banana,Apple,Orange,Lemon,Lime,Mango,Peach,Pineapple,Grapes,Strawberry,...,Nectarine_90,Olive_91,Boysenberry_92,Elderberry_93,Acai_94,Longan_95,Soursop_96,Breadfruit_97,Banana_98,Apple_99
Banana,1.000000,0.671794,0.794864,0.783043,0.635641,0.642799,0.490815,0.650339,0.767816,0.637084,...,0.814318,0.629653,0.601122,0.948297,0.860317,0.664011,0.796941,0.693781,0.680417,0.681187
Apple,0.671794,1.000000,0.754940,0.834058,0.811413,0.713403,0.855440,0.909042,0.902082,0.779543,...,0.738984,0.982455,0.881725,0.738794,0.815318,0.750522,0.900056,0.900660,0.783135,0.725884
Orange,0.794864,0.754940,1.000000,0.965991,0.930044,0.683069,0.789848,0.864445,0.915063,0.906057,...,0.769038,0.726552,0.797326,0.733670,0.609823,0.513730,0.705482,0.824263,0.783111,0.363363
Lemon,0.783043,0.834058,0.965991,1.000000,0.879505,0.733408,0.893205,0.905594,0.926164,0.906387,...,0.764503,0.823684,0.772155,0.785979,0.697643,0.640984,0.738642,0.909523,0.729478,0.491143
Lime,0.635641,0.811413,0.930044,0.879505,1.000000,0.609767,0.774188,0.919377,0.931060,0.922254,...,0.658450,0.766447,0.887004,0.591385,0.505999,0.475982,0.703906,0.791843,0.814754,0.295573
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Longan_95,0.664011,0.750522,0.513730,0.640984,0.475982,0.635675,0.612521,0.736635,0.651886,0.503243,...,0.525755,0.713922,0.432939,0.862371,0.781027,1.000000,0.710788,0.831239,0.452337,0.827222
Soursop_96,0.796941,0.900056,0.705482,0.738642,0.703906,0.832641,0.678617,0.731340,0.826679,0.623321,...,0.892603,0.896569,0.849119,0.807450,0.923447,0.710788,1.000000,0.827271,0.829478,0.850019
Breadfruit_97,0.693781,0.900660,0.824263,0.909523,0.791843,0.848073,0.921160,0.906201,0.872905,0.778200,...,0.763932,0.899837,0.757597,0.800847,0.766780,0.831239,0.827271,1.000000,0.720406,0.692687
Banana_98,0.680417,0.783135,0.783111,0.729478,0.814754,0.607118,0.651570,0.713183,0.733432,0.585904,...,0.884540,0.722348,0.940638,0.613198,0.635380,0.452337,0.829478,0.720406,1.000000,0.492182
Apple_99,0.681187,0.725884,0.363363,0.491143,0.295573,0.715753,0.487700,0.489768,0.545536,0.303010,...,0.690626,0.741282,0.480302,0.800986,0.939220,0.827222,0.850019,0.692687,0.492182,1.000000

In [45]:

# Recommendation function

def recommend_fruits(fruit_name, top_n=2):
    fruit_name = fruit_name.strip().title()
    
    if fruit_name not in similarity_df.index:
        return f"{fruit_name} not found in dataset"
    
    similar = similarity_df[fruit_name].sort_values(ascending=False)
    
    result = similar.iloc[1:top_n+1]
    
    result = (result * 100).round(2)
    
    return result.to_frame(name="Similarity (%)")

In [46]:

print(recommend_fruits("Mango"))

             Similarity (%)
Apricot_68            91.92
Rambutan_87           91.31

In [47]:
print(recommend_fruits("Kiwi"))

         Similarity (%)
Plum              98.51
Coconut           98.07